[build-system]
# With setuptools 50.0.0, 'make .ve' fails.
requires = ["setuptools < 50.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
exclude = """
/.egg
/.git
/.mypy_cache
/.ve
/build
/dist
/parts
/snap
/src/maasui
/src/maas-offline-docs
"""

[tool.isort]
from_first = false
force_grid_wrap = 0
force_sort_within_sections = true
include_trailing_comma = true
known_first_party = """
apiclient
maascli
maasserver
maastesting
metadataserver
provisioningserver
snippets
"""
default_section = "THIRDPARTY"
line_length = 79
multi_line_output = 3
not_skip = "__init__.py"
order_by_type = false
use_parentheses = true

[tool.pytest.ini_options]
testpaths = [
  "src/apiclient",
  "src/maascli"
]
