name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: |
          Thank you for your PR! The code on GitHub is a mirror only and we don't merge PRs here.
          Please create an MP on Launchpad: https://launchpad.net/maas
